tmethod: "fasttree" # iqtree
ft_variant: "auto" # "auto", "veryfasttree", "fasttree" - auto chooses VeryFastTree for threading, FastTree for single-thread
rfaadir: ""
hmmsearch_cutoff: "-E 1e-5"  # e.g.  "-E 1e-10", "--cut_ga" or something else , for UNI56 use --cut_ga
hmmsearch_cpu: "8"
minmarker: "0.1" # 50 percent of markers need to be present
maxsdup: "4"  # genome will be removed if at least one marker is present in more than n copies
maxdupl: "0.3" # percent of markers that can be present in more than single copy
extract_processes: "8"
tree_cpus: "8"
ft_proteintrees: "-spr 4 -mlacc 3 -slownni -lg" #-wag
ft_speciestree: "-spr 4 -mlacc 3 -slownni -lg" #-wag
iq_proteintrees: "LG+F+I+G4" # LG4X -safe -bb -fast
iq_speciestree: "LG+F+I+G4" # LG4X -safe -bb -fast
lengthfilter: "0.5" # remove sequences that are shorter than n%, if 0 keep all, if 0.5 remove shorter than 50% of median, 1 remove shorter than median
mafft_thread: "--thread 8"
mafftv: "" # "-linsi", "-ginsi" ,...
mafft: "" # "--localpair", " --globalpair", " --maxiterate 1000 --genafpair, ..."
trimal_gt: "-gt 0.1" # trim positions that have less than 10 percent information , can add other command line options
